spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.123:3306/security?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  session:
    store-type: none
server:
  port: 8060


ga:
  security:
    browser:
#      loginPage: /demo-signIn.html
      loginType: REDIRECT


security:
  oauth2:
    client:
      client-id: wyc
      client-secret: wyc